---
**Task 1.** У тебе є дані по користувачу за два дні:

- **День 1**: вектор `v1 = (перегляди, лайки, коментарі) = (10, 3, 1)`
- **День 2**: `v2 = (7, 5, 0)`

In [2]:
import numpy as np

v1 = np.array([10, 3, 1])
v2 = np.array([7, 5, 0])

# use operation + in numpy 
# code
total = v1 + v2
print(total)


[17  8  1]


---
Task 1.1 
Дані
У користувача є активність за 3 дні:

- День 1 → `v1 = (12 переглядів, 3 лайки, 1 коментар)`
- День 2 → `v2 = (20, 5, 0)`
- День 3 → `v3 = (8, 2, 1)`

In [3]:
import numpy as np

v1 = np.array([12, 3, 1])
v2 = np.array([20, 5, 0])
v3 = np.array([8, 2, 1])

# use operation + in numpy 
# code
total_2 = v1 + v2 + v3
print(total_2)

[40 10  2]


---
**Task 2.** Є два користувачі зі схожого сегменту:

> u1 = (перегляди, лайки, підписки) = (30, 4, 1) \
> u2 = (20, 6, 0)

Потрібно зрозуміти, чим відрізняється їхня поведінка.

In [4]:
import numpy as np

u1 = np.array([30, 4, 1])
u2 = np.array([20, 6, 0])

# use operation - in numpy
# code
difference = u1 - u2
print(difference)

[10 -2  1]


---
**Task 2.2**
Поведінка користувача за 2 тижні:

Тиждень 1 → w1 = (100 переглядів, 15 лайків, 3 підписки)

Тиждень 2 → w2 = (140, 18, 5)

In [6]:
import numpy as np

w1 = np.array([100, 15, 3])
w2 = np.array([140, 18, 5])

# use operation - in numpy
weekly_difference = w1 - w2
weekly_difference

array([-40,  -3,  -2])

---
**Task 3.1**  З’ясувати, хто “сильніший” за загальною активністю.

Два користувачі: \
u1 = (50 переглядів, 10 лайків, 4 підписки) \
u2 = (70, 5, 1)



In [ ]:
import numpy as np

u1 = np.array([50, 10, 4])
u2 = np.array([70, 5, 1])

normalized_u1 = np.linalg.norm(u1)
normalized_u2 = np.linalg.norm(u2)
# use linalg.norm

print(normalized_u1, normalized_u2)

51.146847410177685 70.18546858146635


---
**Task 4.** Двоє користувачів у просторі ознак:

> u1 = (перегляди, лайки) = (10, 2) \
> u2 = (15, 5)

Потрібно:
> знайти відстань між ними (евклідова), \
> зрозуміти, хто “активніший” у загальному масштабі.

In [12]:
# 1. Відстань між користувачами
u1 = np.array([10, 2])
u2 = np.array([15, 5])
# use np.linalg.norm
# code 

# 2. Рівень активності кожного (довжина вектора)
# use np.linalg.norm
# code 
normalized_u1 = np.linalg.norm(u1)
normalized_u2 = np.linalg.norm(u2)
length = np.linalg.norm(u1 - u2)
print(normalized_u1, normalized_u2)
print(length)

10.198039027185569 15.811388300841896
5.830951894845301


---
**Task 5.** Нормалізація поведінкових фіч перед кластеризацією


In [ ]:
import numpy as np

users = np.array([
    [10, 3, 1],
    [40, 2, 0],
    [20, 5, 2],
    [15, 1, 1],
    [60, 7, 3]
])

# use linalg.norm
# users / by previos step
normalized_users = np.linalg.norm(users)
normal = users / 
normalized_users

np.float64(77.64019577512668)

---
**Task 5.** Оцініть наскільки користувачу підходить товар

In [ ]:
# user data 
#u = (0.2, 0.8, 0.3, 0.1)

# product data
#p = (0.25, 0.75, 0.2, 0.15)


import numpy as np

u = np.array([0.2, 0.8, 0.3, 0.1])
m = np.array([0.25, 0.75, 0.2, 0.15])

score = # use np.dot 
print(score)